### ISSUE TITLE
Failed to parse GibberishDetectDto from LLM: At #input(result): Type casting failed [Boolean].

### ISSUE THREAD

**Issue by totorofly** [jina-ai/jinaai-js#18]
### Issue Description
I encountered a parsing error when trying to use the `JinaAI.optimize` method with the `ernie-bot-4` model. The error seems to be related to type casting for a Boolean value during the parse of `GibberishDetectDto` from the LLM response.

### Code to Reproduce
```javascript
const JinaAI = require("jinaai");

async function main() {
  const jinaai = new JinaAI({
    secrets: {
      "promptperfect-secret":
        "xxxx",
    },
  });

  try {
    const prompts = await jinaai.optimize("写一首关于爱情的诗", {
      targetModel: "ernie-bot-4",
      target_language: "zh-CN",
      previewSettings: {
        temperature: 0.95,
        top_p: 0.8,
      },
      raw: true,
    });

    console.log(prompts.raw.result);
  } catch (err) {
    console.log(err);
  }
}

main();
```

### Error Message

```yaml
[
  {
    error: 'Failed to parse GibberishDetectDto from LLM: At #input(result): Type casting failed [Boolean].',
    input: {
      prompt: '写一首关于爱情的诗',
      targetModel: 'ernie-bot-4',
      features: [],
      iterations: 1,
      uiLanguage: 'en',
      previewSettings: [Object],
      timeout: 20000,
      previewVariables: {},
      targetLanguage: 'en',
      resultCount: 1
    }
  }
]
```

I would appreciate any insights or guidance on resolving this issue. Thank you!
